### ISSUE TITLE
Seams when stitching rendered frames

### ISSUE THREAD

**Issue by kingsushi001** [p2or/blender-renderborder#7]
Hi again

Seems like when I try to add all the images together as one single render, there are seams where
the images come together. Example:

![](https://i.postimg.cc/DzfkpzCY/seams-render.png)

As you can see, there are seams. At this size (1920x1080), it's not that noticeable, but
I want to render at 14000x9000 for print, and at that size it's much more noticeable.

I have tried everything I can think of to eliminate them.
But sadly nothing has worked so far.

Is this something that can be fixed with addon? Or is there something I am missing Blender-side?

**Comment by p2or** [comment]
Hi @kingsushi001,

at first I thought it might be a rounding error caused by add-on but I double-checked the calculations and the add-on works fine, can't find any inaccuracy. When I set everything manually in the datablocks _(Scenes > Scene > Region Max/Min...)_, I get the same values. Do you? 

![Annotation 2022-07-09 225850](https://user-images.githubusercontent.com/512368/178122530-814840f2-0f62-464c-a334-a7477e227a33.png)
Anyway, a good catch. I'd suggest report a bug over at [developer.blender.org](https://developer.blender.org/) and add a padding of 1px in the meantime. Pretty interesting error, please keep me posted.

Cheers,
Christian
